name: Build & Push Images
on: [push]
jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v24
        secrets:
          nixbuild_token: ${{ secrets.nixbuild_token }}
        with:
          filter_builds: '.top_attr == "checks" or .top_attr == "packages"'
  results:
    name: Verify results
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@v6
      - name: Verify build results
        run: |
          diff \
            <(jq . ./examples/using-the-ci-workflow/expected-result.json) \
            <(echo '${{ needs.checks.outputs.results }}' | jq -S .)
