app = 'jupiter-gateway'
primary_region = 'ewr'

[experimental]
cmd = ['/etc/rathole/server.toml']

[build]
image = 'ghcr.io/insipx/jupiter/rathole-server:latest'

[deploy]
strategy = "rolling"
#strategy = 'bluegreen'

[[services]]
protocol = 'tcp'
internal_port = 2333

[[services.ports]]
port = 2333

# Expose public HTTPS
[[services]]
protocol = 'tcp'
internal_port = 8445

[[services.ports]]
port = 443

# Plain HTTP: https redirect for ACME HTTP-01
[[services]]
protocol = "tcp"
internal_port = 8080

[[services.ports]]
port = 80

[[files]]
guest_path = '/etc/rathole/server.toml'
secret_name = 'RATHOLE_CONFIG'

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
