[server]
bind_addr = "0.0.0.0:2333"
default_token = "YOUR_SECRET_TOKEN_HERE"

heartbeat_interval = 30

[server.transport]
type = "noise"

[server.transport.noise]
local_private_key = "SERVER_PRIVATE_KEY_BASE64"

[server.services.public]
bind_addr = "0.0.0.0:8445"
