{
 "title": "OPNsense GeoIP Maps Copy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "North America",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"block\"} | geoip_location_latitude != \"\" | geoip_location_longitude > -130 | geoip_location_longitude < -60 | geoip_location_latitude > 24 | geoip_location_latitude < 50 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"pass\"} | geoip_location_latitude != \"\" | geoip_location_longitude > -130 | geoip_location_longitude < -60 | geoip_location_latitude > 24 | geoip_location_latitude < 50 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    }
   ]
  },
  {
   "title": "Europe",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"block\"} | geoip_location_latitude != \"\" | geoip_location_longitude > -25 | geoip_location_longitude < 60 | geoip_location_latitude > 35 | geoip_location_latitude < 72 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"pass\"} | geoip_location_latitude != \"\" | geoip_location_longitude > -25 | geoip_location_longitude < 60 | geoip_location_latitude > 35 | geoip_location_latitude < 72 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    }
   ]
  },
  {
   "title": "East Asia",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 7, "x": 15, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"block\"} | geoip_location_latitude != \"\" | geoip_location_longitude > 60 | geoip_location_longitude < 150 | geoip_location_latitude > 5 | geoip_location_latitude < 55 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"pass\"} | geoip_location_latitude != \"\" | geoip_location_longitude > 60 | geoip_location_longitude < 150 | geoip_location_latitude > 5 | geoip_location_latitude < 55 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    }
   ]
  },
  {
   "title": "Africa",
   "type": "geomap",
   "gridPos": { "h": 26, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"block\"} | geoip_location_latitude != \"\" | geoip_location_longitude > -20 | geoip_location_longitude < 55 | geoip_location_latitude > -35 | geoip_location_latitude < 38 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"pass\"} | geoip_location_latitude != \"\" | geoip_location_longitude > -20 | geoip_location_longitude < 55 | geoip_location_latitude > -35 | geoip_location_latitude < 38 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    }
   ]
  },
  {
   "title": "Australia / Oceania",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 6, "x": 8, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"block\"} | geoip_location_latitude != \"\" | geoip_location_longitude > 110 | geoip_location_longitude < 180 | geoip_location_latitude > -50 | geoip_location_latitude < -10 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"pass\"} | geoip_location_latitude != \"\" | geoip_location_longitude > 110 | geoip_location_longitude < 180 | geoip_location_latitude > -50 | geoip_location_latitude < -10 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    }
   ]
  },
  {
   "title": "South America",
   "type": "geomap",
   "gridPos": { "h": 30, "w": 5, "x": 14, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"block\"} | geoip_location_latitude != \"\" | geoip_location_longitude > -85 | geoip_location_longitude < -30 | geoip_location_latitude > -60 | geoip_location_latitude < 15 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (geoip_location_latitude, geoip_location_longitude, geoip_country_name, geoip_city_name) (count_over_time({app=\"filterlog\", action=\"pass\"} | geoip_location_latitude != \"\" | geoip_location_longitude > -85 | geoip_location_longitude < -30 | geoip_location_latitude > -60 | geoip_location_latitude < 15 [$__range]))",
     "legendFormat": "{{geoip_city_name}}, {{geoip_country_name}}"
    }
   ]
  }
 ]
}