{
 "title": "Unbound DNS",
 "description": "Unbound metrics & logs dashboard using Prometheus and Loki",
 "tags": [
  "unbound",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki", "query": "loki" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unbound_queries_total{job=\"unbound\"})",
     "legendFormat": "Total Queries"
    },
    {
     "expr": "sum(unbound_cache_hits_total{job=\"unbound\"})",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "sum(unbound_cache_misses_total{job=\"unbound\"})",
     "legendFormat": "Cache Miss"
    },
    {
     "expr": "sum(unbound_prefetches_total{job=\"unbound\"})",
     "legendFormat": "Prefetch"
    },
    {
     "expr": "sum(unbound_expired_total{job=\"unbound\"})",
     "legendFormat": "Expired"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_time_up_seconds_total{job=\"unbound\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(unbound_request_list_current_user{job=\"unbound\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "unbound_recursion_time_seconds_avg{job=\"unbound\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unbound_request_list_max{job=\"unbound\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unbound_request_list_avg{job=\"unbound\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"unbound\"}",
     "legendFormat": "Metrics"
    },
    {
     "expr": "scrape_duration_seconds{job=\"unbound\"}",
     "legendFormat": "Scrape"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 2, "w": 1, "x": 0, "y": 3 }, "fieldConfig": { "defaults": { "unit": "locale" } }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 1, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_blocklist_domain_count{job=\"unbound\"}",
     "legendFormat": "Blocklist Domains"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unbound_cache_hits_total{job=\"unbound\"})",
     "legendFormat": "hit"
    },
    {
     "expr": "sum(unbound_cache_misses_total{job=\"unbound\"})",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_query_udpout_total{job=\"unbound\"}",
     "legendFormat": "UDP Out"
    },
    {
     "expr": "unbound_query_tcpout_total{job=\"unbound\"}",
     "legendFormat": "TCP Out"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unbound_memory_caches_bytes{job=\"unbound\"})",
     "legendFormat": "Cache Mem"
    },
    {
     "expr": "sum(unbound_memory_modules_bytes{job=\"unbound\"})",
     "legendFormat": "Modules Mem"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_msg_cache_count{job=\"unbound\"}",
     "legendFormat": "Msg Cache"
    },
    {
     "expr": "unbound_rrset_cache_count{job=\"unbound\"}",
     "legendFormat": "RRset Cache"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_infra_cache_count{job=\"unbound\"}",
     "legendFormat": "Infra Cache"
    },
    {
     "expr": "unbound_key_cache_count{job=\"unbound\"}",
     "legendFormat": "Key Cache"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 2, "w": 1, "x": 19, "y": 3 }, "fieldConfig": { "defaults": { "unit": "locale" } }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "⧉ Response Time Buckets", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 5 } },
  { "title": "⧉ Recursion Time", "type": "text", "gridPos": { "h": 1, "w": 7, "x": 8, "y": 5 } },
  {
   "title": "⧉ Live Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(client_ip) (count_over_time({app=\"unbound\"} |~ \"reply:\" | client_ip != \"\"  [$__interval]))",
     "legendFormat": "{{client_ip}}",
     "resolution": 1
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_response_time_seconds_bucket{job=\"unbound\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "unbound_recursion_time_seconds_avg{job=\"unbound\"}",
     "legendFormat": "Avg"
    },
    {
     "expr": "unbound_recursion_time_seconds_median{job=\"unbound\"}",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "⧉ Query Types",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_query_types_total{job=\"unbound\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "⧉ Response",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_answer_rcodes_total{job=\"unbound\"} > 0",
     "legendFormat": "{{rcode}}"
    },
    {
     "expr": "unbound_answers_secure_total{job=\"unbound\"} > 0",
     "legendFormat": "secure"
    },
    {
     "expr": "unbound_answers_bogus{job=\"unbound\"} > 0",
     "legendFormat": "bogus"
    }
   ]
  },
  {
   "title": "⧉ Queries",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({app=\"unbound\"} |~ \"reply:\" [$__range]))"
    },
    {
     "expr": "sum by(app) (count_over_time({app=\"unbound\"} |~ \"NXDOMAIN\" [$__range]))"
    }
   ]
  },
  {
   "title": "⧉ Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({app=\"unbound\"} |~ \"reply:\" [$__interval])",
     "legendFormat": "{{dns}}",
     "resolution": 1
    },
    {
     "expr": "count_over_time({app=\"unbound\"} |~ \"NXDOMAIN\" [$__interval])",
     "legendFormat": "{{dns}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "⧉ Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({app=\"unbound\"} |~ \"reply:\"  [$__interval])",
     "legendFormat": "{{client_ip}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "⧉ Top Client Queries",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(query_domain, client_ip) (count_over_time({app=\"unbound\"} |~ \"reply:\" | client_ip != \"\" | query_domain != \"\"  [$__range]))"
    }
   ]
  },
  {
   "title": "⧉ Top Blocked",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "sum by(query_domain) (count_over_time({app=\"unbound\"} |~ \"NXDOMAIN\" | query_domain != \"\"  [$__range]))"
    }
   ]
  },
  {
   "title": "⧉ Live Queries",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{app=\"unbound\"} |~ \"reply:\" "
    }
   ]
  },
  {
   "title": "⧉ Live Blocked",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 11, "y": 37 },
   "targets": [
    {
     "expr": "{app=\"unbound\"} |~ \"NXDOMAIN\" "
    }
   ]
  }
 ]
}